apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegen
  janus-idp.io/tekton: codegen
  backstage.io/kubernetes-id: codegen
  backstage.io/kubernetes-namespace: codegen 
  app.kubernetes.io/part-of: codegen
resources: 
#
# - initialize-namespace.yaml
#
- deployment.yaml
- route.yaml
- service.yaml
