apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: codegen
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen 
  name: codegen
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: llamacpp-svc
    weight: 100 
  wildcardPolicy: None


# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   name: llamacpp-route
#   namespace: test-proj
# spec:
#   host: llamacpp.apps.rosa.f5mm6-ny5i2-ai4.1uvd.p3.openshiftapps.com
#   port:
#     targetPort: 8501
#   to:
#     kind: Service
#     name: llamacpp-svc
#     weight: 100
#   wildcardPolicy: None
